version: "2"

services:
  laravel-php82:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile
      args:
        - PHP_VERSION=8.2
    environment:
      - MYSQL_ADMIN_PASS=password
      - MYSQL_USER_NAME=laravel
      - MYSQL_USER_PASS=password
      - MYSQL_USER_DB=laravelapp
    ports:
      - "3040:80"
      - "3041:3306"
    tmpfs:
      - /var/lib/mysql
    volumes:
      - app:/app
